version: "3.8"

services:
  mysql_db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hw
      MYSQL_USER: secret
      MYSQL_PASSWORD: secret